import mongoose, { Schema } from 'mongoose';

const Expense_Schema = new mongoose.Schema(
    {
        user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'user_tables', index: true },
        title: { type: String },
        amount: { type: Number },
        category: { type: String },
        date: { type: Date, index: true },
        lastProcessedDate: { type: Date },
        notes: { type: String },
        type: { type: String, default: 'Expense' },
        frequency: {
            type: String,
            enum: ['Daily', 'Weekly', 'Monthly', 'Yearly']
        },

        isActive: {
            type: Boolean,
            default: false,
            index: true
        },

        isAutoGenerated: {
            type: Boolean,
            default: false,
            index: true
        },

        enddate: {
            type: Date,
            default: null
        },
        googleEventId: { type: String, default: null },
        isEventCreated: { type: Boolean, default: false }
    },
    { timestamps: true }
);

Expense_Schema.index({ isActive: 1, isAutoGenerated: 1, date: 1 });

export const Expense_Model = mongoose.model('Expense_Table', Expense_Schema);
